return {
  version = "1.4",
  luaversion = "5.1",
  tiledversion = "1.4.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 50,
  height = 50,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 6,
  nextobjectid = 9,
  properties = {},
  tilesets = {
    {
      name = "set",
      firstgid = 1,
      filename = "set.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 40,
      image = "RPGpack_sheet.png",
      imagewidth = 1280,
      imageheight = 832,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 1040,
      tiles = {
        {
          id = 748,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 749,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 788,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 789,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 828,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 829,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 868,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 869,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 908,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 909,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 924,
          properties = {
            ["collidable"] = false
          },
          objectGroup = {
            type = "objectgroup",
            draworder = "index",
            id = 2,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            properties = {},
            objects = {
              {
                id = 1,
                name = "",
                type = "",
                shape = "polygon",
                x = 9.08005,
                y = 0.358423,
                width = 0,
                height = 0,
                rotation = 0,
                visible = true,
                polygon = {
                  { x = 0, y = 0 },
                  { x = 22.5806, y = 0.119474 },
                  { x = 22.5806, y = 30.7049 },
                  { x = 12.3059, y = 30.9438 }
                },
                properties = {}
              }
            }
          }
        },
        {
          id = 925,
          properties = {
            ["collidable"] = false
          },
          objectGroup = {
            type = "objectgroup",
            draworder = "index",
            id = 2,
            name = "",
            visible = true,
            opacity = 1,
            offsetx = 0,
            offsety = 0,
            properties = {},
            objects = {
              {
                id = 2,
                name = "",
                type = "",
                shape = "polygon",
                x = 21.8638,
                y = 30.8243,
                width = 0,
                height = 0,
                rotation = 180,
                visible = true,
                polygon = {
                  { x = 0, y = 30.9438 },
                  { x = 21.6248, y = 30.8243 },
                  { x = 21.8638, y = -1.17567 },
                  { x = 5.86375, y = -1.17567 }
                },
                properties = {}
              }
            }
          }
        },
        {
          id = 948,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 949,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 971,
          animation = {
            {
              tileid = 841,
              duration = 100
            },
            {
              tileid = 843,
              duration = 100
            },
            {
              tileid = 845,
              duration = 100
            },
            {
              tileid = 847,
              duration = 100
            },
            {
              tileid = 849,
              duration = 100
            },
            {
              tileid = 851,
              duration = 100
            }
          }
        },
        {
          id = 988,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 989,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 1028,
          properties = {
            ["doors"] = "bloop"
          }
        },
        {
          id = 1029,
          properties = {
            ["doors"] = "bloop"
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 50,
      height = 50,
      id = 1,
      name = "Background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["testing"] = "yup"
      },
      encoding = "base64",
      data = "UwAAAFMAAAAHAAAAUwAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAABTAAAAUwAAAAcAAABTAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAABTAAAABwAAAFMAAABTAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAFMAAABTAAAAUwAAAFMAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAAUwAAAFMAAABTAAAAUwAAAAgAAABTAAAAUwAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAABTAAAAUwAAAFMAAABTAAAAUwAAAFMAAABTAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAcAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAFMAAABTAAAAUwAAAFMAAABTAAAAUwAAAFMAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAABwAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAFMAAABTAAAAUwAAAFMAAABTAAAAUwAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAAUwAAAFMAAABTAAAAUwAAAFMAAABTAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAABTAAAAUwAAAFMAAABTAAAAUwAAAFMAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAFMAAABTAAAAUwAAAFMAAABTAAAAUwAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAAUwAAAFMAAABTAAAAUwAAAFMAAABTAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAABTAAAAUwAAAFMAAABTAAAAUwAAAFMAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAFMAAABTAAAAUwAAAAgAAABTAAAAUwAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAAUwAAAFMAAABTAAAACAAAAFMAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAABTAAAAUwAAAFMAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAFMAAABTAAAAUwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAABTAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAFMAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAAcAAAAIAAAABwAAAAgAAAAHAAAACAAAAA=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 50,
      height = 50,
      id = 2,
      name = "Midground",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACUDAAAmAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABwAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATQMAAE4DAAAAAAAAAAAAAAAAAAAAAAAA7QIAAO4CAAAHAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1AwAAdgMAAAAAAAAAAAAAAAAAAAAAAAAVAwAAFgMAAAcAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ0DAACeAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACUDAAAmAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATQMAAE4DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1AwAAdgMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ0DAACeAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "ObjectDraw",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["collidable"] = false
      },
      objects = {
        {
          id = 4,
          name = "",
          type = "",
          shape = "polygon",
          x = 134.226,
          y = 261.54,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 14.5502, y = 15.2777 },
            { x = 23.2803, y = 38.9218 },
            { x = 25.8266, y = 83.6637 },
            { x = 13.8227, y = 93.4851 },
            { x = 1.81878, y = 106.217 },
            { x = 1.81878, y = 120.403 },
            { x = -17.0965, y = 120.767 },
            { x = -16.0052, y = 99.669 },
            { x = -30.9192, y = 89.8476 },
            { x = -39.2856, y = 69.4773 },
            { x = -39.2856, y = 48.3795 },
            { x = -33.1017, y = 30.9192 },
            { x = -19.279, y = 5.45633 },
            { x = -78.9349, y = -11.2764 },
            { x = 50.1982, y = -21.0978 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Doors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 176,
          width = 40,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {
            ["Destination"] = "inn"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "PlayerSpawn",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 8,
          name = "",
          type = "",
          shape = "point",
          x = 272,
          y = 312,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
